version: "3.7"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - app-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - app-redis:/var/lib/redis/data

  app:
    build:
      context: src
      args:
        USER_ID: "${RAILS_APP_UID:-1000}"
        GROUP_ID: "${RAILS_APP_GID:-1000}"
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./src
        target: /opt/app/
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        USER_ID: "${RAILS_APP_UID:-1000}"
        GROUP_ID: "${RAILS_APP_GID:-1000}"
    command: bundle exec sidekiq 
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./src
        target: /opt/app
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - app
    ports:
      # - '80:8020'
      - '8020:8020'

volumes:
  app-postgres:
  app-redis: