version: "3.8"

services:

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - app-postgres:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    ports:
      - '6379:6379'
    volumes:
      - app-redis:/var/lib/redis/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        RAILS_APP_USER: ${RAILS_APP_USER}
        RAILS_APP_GROUP: ${RAILS_APP_GROUP}
        RAILS_APP_UID: ${RAILS_APP_UID}
        RAILS_APP_GID: ${RAILS_APP_GID}
        RAILS_APP_DIR: ${RAILS_APP_DIR}
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./src
        target: /opt/app/
    ports:
      - '8010:8010'

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile-app
      args:
        RAILS_APP_USER: ${RAILS_APP_USER}
        RAILS_APP_GROUP: ${RAILS_APP_GROUP}
        RAILS_APP_UID: ${RAILS_APP_UID}
        RAILS_APP_GID: ${RAILS_APP_GID}
        RAILS_APP_DIR: ${RAILS_APP_DIR}
    command: bundle exec sidekiq 
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./src
        target: /opt/app

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - app
    ports:
      # - '80:8020'
      - '8020:8020'

volumes:
  app-postgres:
  app-redis: